/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package B;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author LENOVO
 */
public class CAdd extends javax.swing.JInternalFrame {

    ConnectDB c=new ConnectDB();
     public Connection conn=c.getConn();
     public ResultSet rs=null;
    PreparedStatement pst=null;
    
    public CAdd() {
        initComponents();
        cno();
        addCombo();
        
        
    }

   
     public void addCombo(){
        try{
        
        String sql="SELECT name, location, contact, birthdate\n" +
"	FROM public.\"Customers_List\";";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        
        while(rs.next()){
            String menu=rs.getString(1);
            cb1.addItem(menu);
        }
        }catch(Exception e){
            
        }
        
    }
     
     
  
      
    
    void cno(){
         try{
    Connection conn=c.getConn();
    Statement st=conn.createStatement();
    
    String query="SELECT count(name)\n" +
"	FROM public.\"Customers_List\";";
    String no="";
    rs=st.executeQuery(query);
    if(rs != null)
    {
        while(rs.next()){
            no=rs.getString(1);
            
        }
         
        l1.setText(no);
    }
}   catch(Exception e){
    JOptionPane.showMessageDialog(null, e);

}        
        
         }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        b1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        l1 = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox<>();
        b3 = new javax.swing.JButton();
        t5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 255));
        setClosable(true);
        setPreferredSize(new java.awt.Dimension(295, 388));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 0, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("New Customer :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 564, 30);

        t1.setBackground(new java.awt.Color(204, 255, 255));
        t1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        t1.setForeground(new java.awt.Color(0, 51, 204));
        t1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t1.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        t1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t1KeyPressed(evt);
            }
        });
        getContentPane().add(t1);
        t1.setBounds(120, 80, 130, 30);

        t2.setBackground(new java.awt.Color(204, 255, 255));
        t2.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        t2.setForeground(new java.awt.Color(0, 51, 204));
        t2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t2.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        t2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t2KeyPressed(evt);
            }
        });
        getContentPane().add(t2);
        t2.setBounds(120, 120, 130, 30);

        t3.setBackground(new java.awt.Color(204, 255, 255));
        t3.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        t3.setForeground(new java.awt.Color(0, 51, 204));
        t3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t3.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        t3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t3KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t3KeyTyped(evt);
            }
        });
        getContentPane().add(t3);
        t3.setBounds(120, 160, 130, 30);

        b1.setBackground(new java.awt.Color(153, 102, 255));
        b1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        b1.setForeground(new java.awt.Color(255, 255, 255));
        b1.setText("AdD");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(10, 290, 110, 30);

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Location  :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 120, 111, 30);

        l2.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        l2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(l2);
        l2.setBounds(20, 330, 240, 20);

        jLabel6.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("BirthDate");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 240, 111, 25);

        jLabel7.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Contact   :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 160, 111, 30);

        jPanel2.setBackground(new java.awt.Color(153, 0, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 564, 30);

        l1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        l1.setForeground(new java.awt.Color(0, 51, 51));
        l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l1.setText("saved :");
        l1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(l1);
        l1.setBounds(200, 30, 70, 30);

        cb1.setBackground(new java.awt.Color(204, 255, 255));
        cb1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        cb1.setForeground(new java.awt.Color(102, 0, 153));
        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "search" }));
        cb1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cb1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(cb1);
        cb1.setBounds(0, 30, 130, 30);

        b3.setBackground(new java.awt.Color(153, 102, 255));
        b3.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        b3.setForeground(new java.awt.Color(255, 255, 255));
        b3.setText("Update ");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3);
        b3.setBounds(160, 290, 100, 30);

        t5.setBackground(new java.awt.Color(204, 255, 255));
        t5.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        t5.setForeground(new java.awt.Color(0, 51, 204));
        t5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t5.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        t5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t5KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t5KeyTyped(evt);
            }
        });
        getContentPane().add(t5);
        t5.setBounds(120, 200, 130, 30);

        jLabel8.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("E-Mail       :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 200, 111, 30);

        jLabel9.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Name         :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 80, 111, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed

        
        String name=t1.getText();
                String  loc=t2.getText();
                String con=t3.getText();
                String em=t5.getText();
                 SimpleDateFormat s= new SimpleDateFormat("dd-MM-yyyy");
                String bday=s.format(t4.getDate());
        
        
        try{
        if(t1.getText().equals(""))
        {
            
            
            t1.requestFocus();
            return;
        }
             if(t2.getText().equals(""))
        {
           
            t2.requestFocus();
            return;
        }
                if(t3.getText().equals(""))
        {
            t3.requestFocus();
            return;
        }
                if(t5.getText().equals(""))
        {
            t5.setText("Not Specify");
            return;
        }
                 if(t4.getDateFormatString().equals(""))
        {
            t4.requestFocus();
            return;
        }
                
                    
                
           
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"Failed "+ex);
            Logger.getLogger(CAdd.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        {
            try{
                String query="INSERT INTO public.\"Customers_List\"(\n" +
"	name, location, contact, birthdate, email)\n" +
"	VALUES (?, ?, ?, ?, ?);";
                PreparedStatement pst;
                pst = conn.prepareStatement(query);
                pst.setString(1,name);
                pst.setString(2,loc);
                pst.setString(3,con);
                pst.setString(4,bday);
                pst.setString(5,em);
                
               

                pst.execute();
                l2.setText("SuccessFully Added..!!");
               
                t2.setText(""); t1.setText("");
                t5.setText("");
                t3.setText("");
                 t4.setDateFormatString("");
                 cno();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
            
        }
    }//GEN-LAST:event_b1ActionPerformed

    private void t2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t2KeyPressed
 if(evt.getKeyCode()==KeyEvent.VK_ENTER)
{
     t3.requestFocus();
    
}        // TODO add your handling code here:
    }//GEN-LAST:event_t2KeyPressed

    private void t3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t3KeyPressed
 if(evt.getKeyCode()==KeyEvent.VK_ENTER)
{
    t4.requestFocus();
    
}        // TODO add your handling code here:
    }//GEN-LAST:event_t3KeyPressed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
   
    }//GEN-LAST:event_t2ActionPerformed

    private void t1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1KeyPressed

        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            t2.requestFocus();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_t1KeyPressed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void cb1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cb1PopupMenuWillBecomeInvisible
        String a=cb1.getSelectedItem().toString();
                String sql="SELECT name, location, contact, birthdate\n" +
"	FROM public.\"Customers_List\" WHERE name=?        ; ";
            
            try{
               
                pst=conn.prepareStatement(sql);
                pst.setString(1, a);
                rs= pst.executeQuery();
                if(rs.next())
                {
                    t1.setText(rs.getString(1));
                    t2.setText(rs.getString(2));
                    t3.setText(rs.getString(4));
                    t4.setDateFormatString(rs.getString(2));
                    
                }
            }catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            };        // TODO add your handling code here:
    }//GEN-LAST:event_cb1PopupMenuWillBecomeInvisible

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
                String name=t1.getText();
                String  loc=t2.getText();
                String con=t3.getText();
                String bday=t4.getDateFormatString();
        
    try{
      
     String sql="UPDATE public.\"Customers_List\"\n" +
"	SET name='"+name+"', location='"+loc+"', contact='"+con+"', birthdate='"+bday+"'\n" +
"	WHERE name='"+name +"'    ;";
     pst=conn.prepareStatement(sql);
                pst.execute();
                 JOptionPane.showMessageDialog(null, "  Updated as  ");
               
            }catch(Exception e){JOptionPane.showMessageDialog(null, e);};
                    // TODO add your handling code here:
    }//GEN-LAST:event_b3ActionPerformed

    private void t3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t3KeyTyped
char c=evt.getKeyChar();
        if(!(Character.isDigit(c)) || (c==KeyEvent.VK_ENTER) ||(c==KeyEvent.VK_BACK_SPACE)   ){
            evt.consume();}        // TODO add your handling code here:
    }//GEN-LAST:event_t3KeyTyped

    private void t5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t5KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t5KeyPressed

    private void t5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t5KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_t5KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b3;
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t5;
    // End of variables declaration//GEN-END:variables
}
