/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package B;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class Create_user extends javax.swing.JInternalFrame {

    ConnectDB c=new ConnectDB();
    public Connection conn=c.getConn();
     public ResultSet rs=null;
    PreparedStatement pst=null;
    /**
     * Creates new form a
     */
    public Create_user() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        b1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(100, 255, 120));
        setClosable(true);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(51, 255, 51));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Create New User");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, -10, 200, 50);

        l1.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        l1.setForeground(new java.awt.Color(255, 255, 255));
        l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l1.setText("jLabel5");
        jPanel2.add(l1);
        l1.setBounds(560, 10, 160, 20);

        l2.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        l2.setForeground(new java.awt.Color(255, 255, 255));
        l2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l2.setText("jLabel5");
        jPanel2.add(l2);
        l2.setBounds(740, 10, 160, 20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 530, 30);

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jLabel4.setText("UserName");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(200, 40, 110, 30);

        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jLabel5.setText("password");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(200, 80, 90, 30);

        jLabel7.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jLabel7.setText("mobil no.");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(200, 120, 70, 30);

        jLabel6.setBackground(new java.awt.Color(200, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/B/login1d.png"))); // NOI18N
        jLabel6.setText("jLabel3");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 40, 130, 140);

        t1.setBackground(new java.awt.Color(240, 255, 255));
        t1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t1KeyPressed(evt);
            }
        });
        getContentPane().add(t1);
        t1.setBounds(310, 40, 140, 30);

        t2.setBackground(new java.awt.Color(240, 255, 255));
        t2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t2KeyPressed(evt);
            }
        });
        getContentPane().add(t2);
        t2.setBounds(310, 80, 140, 30);

        t3.setBackground(new java.awt.Color(240, 255, 255));
        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        t3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t3KeyPressed(evt);
            }
        });
        getContentPane().add(t3);
        t3.setBounds(310, 120, 140, 30);

        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/B/resisternow.png"))); // NOI18N
        b1.setText("jLabel6");
        b1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b1MouseClicked(evt);
            }
        });
        b1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                b1KeyPressed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(240, 160, 150, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t2KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            t3.requestFocus();

        }         // TODO add your handling code here:
    }//GEN-LAST:event_t2KeyPressed

    private void t3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t3KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
             try{
            String n1=t1.getText();
            String n2=t2.getText();
            String n3=t1.getText();

            String query="INSERT INTO public.\"User\"(\n" +
            "	username, password, phno)\n" +
            "	VALUES (?, ?, ?);";
            PreparedStatement pst;
            pst = conn.prepareStatement(query);
            pst.setString(1,n1);
            pst.setString(2,n2);

            pst.setString(3,n3);

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"ok");
            t1.setText("");
            t2.setText("");
            t1.setText("");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }

        }         // TODO add your handling code here:
    }//GEN-LAST:event_t3KeyPressed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    private void b1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MouseClicked

        try{
            String n1=t1.getText();
            String n2=t2.getText();
            String n3=t3.getText();

            String query="INSERT INTO public.\"User\"(\n" +
            "	username, password, phno)\n" +
            "	VALUES (?, ?, ?);";
            PreparedStatement pst;
            pst = conn.prepareStatement(query);
            pst.setString(1,n1);
            pst.setString(2,n2);

            pst.setString(3,n3);

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"ok");
            t1.setText("");
            t2.setText("");
            t3.setText("");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_b1MouseClicked

    private void b1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b1KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            try{
                String n1=t1.getText();
                String n2=t2.getText();
                String n3=t3.getText();

                String query="INSERT INTO public.\"User\"(\n" +
                "	username, password, phno)\n" +
                "	VALUES (?, ?, ?);";
                PreparedStatement pst;
                pst = conn.prepareStatement(query);
                pst.setString(1,n1);
                pst.setString(2,n2);

                pst.setString(3,n3);

                pst.executeUpdate();
                JOptionPane.showMessageDialog(null,"ok");
                t1.setText("");
                t2.setText("");
                t3.setText("");
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }

        }         // TODO add your handling code here:
    }//GEN-LAST:event_b1KeyPressed

    private void t1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            t2.requestFocus();

        }         // TODO add your handling code here:
    }//GEN-LAST:event_t1KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    // End of variables declaration//GEN-END:variables
}
